name: Sync Leetcode

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ secrets._GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets._LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets._LEETCODE_SESSION }}
          destination-folder: leetcode-destination-folder
